services:
  grafana:
    user: root
    container_name: 'fiftyone-britewyn-app'

    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-11.3.2}
        development: ${DEVELOPMENT:-false}
        anonymous_auth_enabled: ${ANONYMOUS_AUTH_ENABLED:-true}
    ports:
      - 3005:3000/tcp
      - 2346:2345/tcp # delve
    security_opt:
      - 'apparmor:unconfined'
      - 'seccomp:unconfined'
    cap_add:
      - SYS_PTRACE
    volumes:
      - ./dist:/var/lib/grafana/plugins/fiftyone-britewyn-app
      - ./provisioning:/etc/grafana/provisioning
      - .:/root/fiftyone-britewyn-app

    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.fiftyone-britewyn-app:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: fiftyone-britewyn-app
